name: Validate PR Metadata
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened

jobs:
  validate_pr_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: illicitonion/CYF-actions/validate-pr-metadata@main
